version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-User
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
